version: '3.8'

services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    # Порт 8000 больше не публикуется наружу. Nginx будет общаться с ним внутри Docker.

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    # Порт 8080 также скрыт от внешнего мира.

  bot:
    build:
      context: ./bot
    restart: unless-stopped
    env_file:
      - ./bot/.env

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Монтируем нашу кастомную конфигурацию Nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Монтируем SSL-сертификаты в режиме "только для чтения" для безопасности
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend