services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on: []
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "8080:8080"
    depends_on: []

  bot:
    build: ./bot
    env_file:
      - ./bot/.env
    depends_on: [] 