# docker-compose.yml (ИСПРАВЛЕННАЯ ВЕРСИЯ)
version: '3.8' # Рекомендуется указывать версию

services:
  backend:
    build:
      context: ./backend # Используем более явный синтаксис
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on: []
    # volumes: # <-- ЗАКОММЕНТИРУЙТЕ ИЛИ УДАЛИТЕ ЭТУ СТРОКУ
    #   - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "8080:8080"
    depends_on: []
    # У фронтенда не было этой проблемы, но структура с context - лучше.

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - ./bot/.env
    depends_on: []