services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=surveyuser
      - POSTGRES_PASSWORD=surveypass
      - POSTGRES_DB=surveydb
    volumes:
      - pgdata2:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    environment:
      - SYNC_DATABASE_URL=postgresql://surveyuser:surveypass@db:5432/surveydb
      - ASYNC_DATABASE_URL=postgresql+asyncpg://surveyuser:surveypass@db:5432/surveydb
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=http://localhost:8000/auth/google/callback
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata2:
