services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: surveyuser
      POSTGRES_PASSWORD: surveypass
      POSTGRES_DB: surveydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+psycopg2://surveyuser:surveypass@db:5432/surveydb
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
