"""add tg_user_id and tg_link_code to user

Revision ID: b71a05a3277c
Revises: df15b9dc38e0
Create Date: 2025-06-24 12:13:43.102959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71a05a3277c'
down_revision: Union[str, None] = 'df15b9dc38e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_user_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tg_link_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_tg_link_code'), 'users', ['tg_link_code'], unique=True)
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_tg_link_code'), table_name='users')
    op.drop_column('users', 'tg_link_code')
    op.drop_column('users', 'tg_user_id')
    # ### end Alembic commands ###
