"""add public_id field to survey

Revision ID: d5d81c35c0ee
Revises: a315e65cce00
Create Date: 2025-06-17 06:58:05.673452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d81c35c0ee'
down_revision: Union[str, None] = 'a315e65cce00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('public_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_surveys_public_id'), 'surveys', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surveys_public_id'), table_name='surveys')
    op.drop_column('surveys', 'public_id')
    # ### end Alembic commands ###
