"""add public_id field to survey

Revision ID: d5d81c35c0ee
Revises: a315e65cce00
Create Date: 2025-06-17 06:58:05.673452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import secrets


# revision identifiers, used by Alembic.
revision: str = 'd5d81c35c0ee'
down_revision: Union[str, None] = 'a315e65cce00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('public_id', sa.String(), nullable=True))

    conn = op.get_bind()
    surveys = conn.execute(sa.text("SELECT id FROM surveys WHERE public_id IS NULL"))
    for row in surveys:
        conn.execute(
            sa.text("UPDATE surveys SET public_id = :pid WHERE id = :id"),
            {"pid": secrets.token_urlsafe(6), "id": row.id}
        )

    op.alter_column('surveys', 'public_id', nullable=False)
    op.create_unique_constraint('uq_surveys_public_id', 'surveys', ['public_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_surveys_public_id', 'surveys', type_='unique')
    op.drop_column('surveys', 'public_id')
    # ### end Alembic commands ###
