"""add survey_answers table

Revision ID: df15b9dc38e0
Revises: 5eaafbd09ce1
Create Date: 2025-06-19 07:06:18.973518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df15b9dc38e0'
down_revision: Union[str, None] = '5eaafbd09ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('answers', sa.Text(), nullable=False),
    sa.Column('respondent_id', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_answers_id'), 'survey_answers', ['id'], unique=False)
    op.create_index(op.f('ix_survey_answers_public_id'), 'survey_answers', ['public_id'], unique=False)
    op.create_index(op.f('ix_survey_answers_survey_id'), 'survey_answers', ['survey_id'], unique=False)
    op.drop_constraint(op.f('uq_surveys_public_id'), 'surveys', type_='unique')
    op.create_index(op.f('ix_surveys_public_id'), 'surveys', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surveys_public_id'), table_name='surveys')
    op.create_unique_constraint(op.f('uq_surveys_public_id'), 'surveys', ['public_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_survey_answers_survey_id'), table_name='survey_answers')
    op.drop_index(op.f('ix_survey_answers_public_id'), table_name='survey_answers')
    op.drop_index(op.f('ix_survey_answers_id'), table_name='survey_answers')
    op.drop_table('survey_answers')
    # ### end Alembic commands ###
